## Подготовка данных для занятия

In [3]:
import re

import pandas as pd
import pymorphy2


text_df = pd.read_csv("./content_description.csv", sep='\t')
text_df.head()

# разбиваем тест на слова
corpus = []
# регулярка для поиска слов
regular_expr = r'\w+'
reg_expr_compiled = re.compile(regular_expr)
# формируем датасет из отдельных слов
for raw_text in text_df.description.values:
    # приводим к нижнему регистру
    raw_text_lower = raw_text.lower()
    # разбиваем текст на слова
    text_by_words = reg_expr_compiled.findall(raw_text_lower) 
    corpus.append(text_by_words)

# нормализация текста
normalized_corpus = []
morph = pymorphy2.MorphAnalyzer()
# нормализуем каждое слово в тексте
for token_list in corpus:
    normalized_token_list = []
    for word in token_list:
        parsed_token = morph.parse(word)
        normal_form = parsed_token[0].normal_form
        normalized_token_list.append(normal_form)
    normalized_corpus.append(normalized_token_list)

# превращаем в DataFrame
doc_count = len(normalized_corpus)
doc_ids = []
tokens = []
# формируем два списка-колонки датафрейма
for doc_id in range(doc_count):
    for token in normalized_corpus[doc_id]:
        doc_ids.append(doc_id)
        tokens.append(token)

tokens_df = pd.DataFrame({
    'doc_id': doc_ids,
    'word': tokens
})
# дамми-столбец
tokens_df = tokens_df.assign(dummy = 1)
# аггрегируем статистики
word_count_df = tokens_df.groupby(['doc_id','word'])['dummy'].count().reset_index()

word_count_df[word_count_df.doc_id==0].sort_values(by='dummy', ascending=False).head(10)

     doc_id       word  dummy
6         0          в     10
29        0          и      7
37        0    который      5
111       0     шерлок      4
77        0          с      4
84        0     сериал      4
75        0  риколетти      3
31        0    история      2
21        0        для      2
49        0          о      2

# 10.3  Домашняя работа

10.3.1 **Задание простого уровня** Для каждого слова подсчитайте процент документов, в которых содержится это слово. Сформируйте dataframe doc_frequency. Процен документов вычисляется по формуле
$$
d = \frac{m}{n} \times 100
$$
где $m$ - количество документов, в которых встретилось это слово, а $n$ - общее количество документов. Значение в процентах округлите до целых.

Посмотрите какие слова оказались в топе - это предлоги и частицы. Такие слова присутствуют во всех документах, а значит, их можно удалить из текста, чтобы оставшиеся слова были более "осмысленными". Это упростит анализ текста.

In [23]:
doc_frequency = pd.DataFrame()

doc_frequency = word_count_df.groupby("word")["doc_id"].count().reset_index(
    name = 'doc_freq').sort_values(by="doc_freq", ascending=False)

doc_frequency["doc_freq"] = round(doc_frequency["doc_freq"] / doc_count * 100, 0)


doc_frequency.head(10)

       word  doc_freq
171       и     100.0
41        в     100.0
269      на      88.0
468       с      88.0
323      он      75.0
480    свой      75.0
618     что      75.0
326  онлайн      75.0
283      не      75.0
90      год      62.0

10.3.2 **Задание среднего уровня**

Воспользуйтесь регулярными выражениями, чтобы извлечь из текста все пары **имя+фамилия**.

* неформальное описание регулярки: пара слов идущая друг за другом, каждое из которых начинается с заглавной буквы
* анализировать нужно только `doc_id=3`
* текст берём из исходного датафрейма `text_df`
* заглавная буква в русскоязычном тексте соответствует символьному классу `r'[A-Я]*'`

In [32]:
# -- ВАШ КОД ЗДЕСЬ --
raw_text = text_df.description.values[3]
# регулярка - её нужно поправить
reg_expr = r'[А-Я]{1}\w+\s[А-Я]{1}\w+'
# компилируем регулярное выражение
reg_expr_compiled = re.compile(reg_expr)
# применяем выражение к тексту
for g in reg_expr_compiled.findall(raw_text):
    print(g)

Стивена Фрая
Джоном Дженксом
Теда Уоллеса
Теперь Тед
Вскоре Тед

In [26]:
raw_text

'Экранизация сатирического бестселлера Стивена Фрая, мастерски воплощенная британским режиссером и продюсером Джоном Дженксом.   У Теда Уоллеса было славное прошлое, и вот-вот его книги должны были пополнить стройный ряд томов британских классиков. Но его жуткий характер вкупе с алкоголизмом и мизантропией в запущенной стадии испортили все. Теперь Тед зарабатывает на жизнь тем, что поносит в своих статьях спектакли, которые вообще-то не стоят его внимания. И продолжает пить. Вскоре Тед лишается и этого: его бесконечное ворчание достало всю редакцию.  Готовясь к голодной и бесславной смерти, внезапно Уоллес получает выгодное предложение от своей крестницы Джейн. Девушка недавно излечилась от болезни благодаря чуду и теперь предлагает Теду погостить в аристократическом доме, чтобы осветить происходящие здесь чудеса исцеления.  Старый скептик соглашается из корыстных побуждений и даже представить не может, сколько сюрпризов ему уготовано.  Смотреть онлайн эту комедию о том, что даже самые заядлые скептики тайно готовы верить в невозможное, можно на нашем сайте.'

10.3.3 **Задание сложного уровня**. Словарь `genre_dict` содержит слова, которые являются характерными для того или иного жанра. Пользуясь словарём, а так же таблицей `word_count_df`, сформируйте таблицу двумя колонками `doc_id | genre` с жанрами фильмов.

Для этого нужно
* превратить словарь `genre_dict` в DataFrame формата `word | genre`
* соединить полученный датафрейм с помощью функции `merge` c ранее полученным датафреймом `word_count_df`, котороый содержит распределение слов по документам. Воспользуйтесь методом соединения `inner`
* для каждого документа выбрать жанр документа - это совокупность жанров слов отдельных слов. У одного контента может быть несколько жанров

In [112]:
import itertools
import pandas as pd

genre_dict = {
    'комедия': ['сатирический', 'авантюрный', 'забавный'],
    'мелодрама': ['выбор', 'позор'],
    'сказка': ['приключения', 'милый', 'семейный'],
    'детектив': ['тайна', 'разгадать', 'загадочный'], 
    'триллер': ['ужас', 'зловещий', 'нерв']
}

nested_genres =[[(i, j) for j in genre_dict[i]] for i in genre_dict]
# переводим из словаря к более удобному виду
flatten_genres = list(itertools.chain(*nested_genres))
# создаём DataFrame
genres_df = pd.DataFrame(flatten_genres, columns = ['genre', 'character_word'])

In [114]:
doc_to_genres = pd.DataFrame()
doc_to_genres.insert(0, "doc_id", 0)
doc_to_genres.insert(1, "genre", "")

for i in range(doc_count):
    word_count_df_i = word_count_df[word_count_df["doc_id"] == i]
    genres = "-"
    for word in word_count_df_i.word:
        for genre, character_word in zip(genres_df.genre, genres_df.character_word):
            if (word == character_word):
                if (genres =="-"):
                    genres = genre
                else:
                    if not (genres.find(genre) >-1):
                        genres += ", " + genre
                break

    new_row = {"doc_id" : i, "genre" : genres}
    doc_to_genres = doc_to_genres.append(new_row, ignore_index=True)
    
    
doc_to_genres

C:\Users\Евдаков Алексей\AppData\Local\Temp\ipykernel_21460\1062267257.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  doc_to_genres = doc_to_genres.append(new_row, ignore_index=True)
C:\Users\Евдаков Алексей\AppData\Local\Temp\ipykernel_21460\1062267257.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  doc_to_genres = doc_to_genres.append(new_row, ignore_index=True)
C:\Users\Евдаков Алексей\AppData\Local\Temp\ipykernel_21460\1062267257.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  doc_to_genres = doc_to_genres.append(new_row, ignore_index=True)
C:\Users\Евдаков Алексей\AppData\Local\Temp\ipykernel_21460\1062267257.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  doc_to_genres = doc_to_genres.append(new_row, ignore_index=True)
C:\Users\Евдаков Алексей\AppData\Local\Temp\ipykernel_21460\1062267257.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  doc_to_genres = doc_to_genres.append(new_row, ignore_index=True)
C:\Users\Евдаков Алексей\AppData\Local\Temp\ipykernel_21460\1062267257.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  doc_to_genres = doc_to_genres.append(new_row, ignore_index=True)
C:\Users\Евдаков Алексей\AppData\Local\Temp\ipykernel_21460\1062267257.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  doc_to_genres = doc_to_genres.append(new_row, ignore_index=True)
C:\Users\Евдаков Алексей\AppData\Local\Temp\ipykernel_21460\1062267257.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  doc_to_genres = doc_to_genres.append(new_row, ignore_index=True)

   doc_id              genre
0       0  детектив, триллер
1       1             сказка
2       2          мелодрама
3       3            комедия
4       4            комедия
5       5                  -
6       6            триллер
7       7                  -

In [106]:
# И правда, ничего подходящего нет.
text_df.description.values[7]

'Двое выпускников калифорнийской школы бизнеса ставят перед собой простую и понятную цель – разбогатеть в кратчайшие сроки. В 1983 году они с успехом основывают рискованную финансовую пирамиду и наслаждаются легкими деньгами, пока сами не становятся жертвами более опытного афериста. Правдивую историю о печально известном  «Клубе миллиардеров» перенес на экран режиссер Джеймс Кокс («Шоссе», «Простые истины»). Роли молодых богачей исполнили звезда дилогии «Kingsman» Тэрон Эджертон и Энсел Эльгорт («Малыш на драйве», «Виноваты звезды»). В образе харизматичного негодяя предстал лауреат двух премий «Оскар» Кевин Спейси.  Молодые выпускники Джо Хант и Дин Картни недавно получили экономическое образование и теперь ищут способ, как применить его во взрослом мире. Этот «мир» – блистательный Лос-Анджелес начала 1980-х годов – полон соблазнов и возможностей. Джо и Дин разрабатывают схему, как разбогатеть на чужих инвестициях. Первый легкий заработок кружит им голову, и тогда они решают играть по-крупному. В их инвестиционную сеть ввязываются крупные вкладчики, а бизнес ребят привлекает внимание прожженного дельца Рона Левина. Ему удается перехитрить начинающих аферистов и оставить их с неподъемными долгами.  Криминальную драму, основанную на реальных событиях, «Клуб миллиардеров» можно смотреть онлайн на нашем сайте.'